# Generated by Django 5.0.2 on 2024-02-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='artist',
            field=models.CharField(max_length=255),
        ),
    ]
