# Generated by Django 5.0.2 on 2024-03-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_payment_user_remove_order_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=True),
        ),
    ]
